package com.dasburo.sample.jupiter.demo.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import springfox.documentation.annotations.ApiIgnore;

/**
 * REST controller to get the information of the alerts generated by.
 *
 * @author Ana Esteban Garcia-Navas(<a href="mailto:ags@dasburo.com">ramoni</a>)
 */
@Controller
@ApiIgnore
public class HomeController {

    @RequestMapping("/")
    public String home() {
        return "redirect:swagger-ui.html";
    }
}
